name: "Install UI dependencies"
description: "Install UI dependencies; fail the build if the lock file is not up-to-date"

inputs:
  working_dir:
    description: "Elyra path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Go to working directory
      shell: bash
      run: |
        echo "Step: Go to working directory"
        cd ${{ inputs.working_dir }}
    - name: Install dependencies
      shell: bash
      run: |
        echo "Step: Install dependencies"
        make yarn-install
    - name: "Check yarn.lock"
      shell: bash
      run: |
        echo "Step: Check yarn.lock"
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]
